### ISSUE TITLE
Missing feeds for djangopatterns.com

### ISSUE THREAD

**Issue by exalted** [coordt/djangopatterns.com#1]
Definitely missing feeds for djangopatterns.com... Or am I missing something?

Regards,

**Comment by coordt** [comment]
I have a feed for changes at http://djangopatterns.com/rss/ or http://djangopatterns.com/atom/ . However, since the bulk of the content is in a Sphinx doc, I'm not sure how to include that in an RSS feed.

Does that work for you, or do you have any other ideas?

Thanks,

Corey

**Comment by exalted** [comment]
I see, that's not a blog or anything like it and yeah... that kinda works! It would be awesome if you could include also body of the entries too.

Thanks for the tip though.

**Comment by coordt** [comment]
For new articles, I'll include the entirety of the article. For updates and such, I'll just mention the changes.

**Comment by exalted** [comment]
Fair enough, thanks a bunch!
